# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='request_body_format',
            field=models.CharField(choices=[('json', 'JSON'), ('form-data', 'Form Data')], default='json', max_length=20),
        ),
    ]
