# Generated by Django 4.2.7 on 2023-11-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0002_testcase_request_body_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='extract_params',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
