# Generated by Django 4.2.7 on 2025-05-09 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0003_testcase_extract_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuitcase',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_suite_cases', to='test_manager.environment'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='test_manager.environment'),
            preserve_default=False,
        ),
    ]
