# Generated by Django 4.2.7 on 2025-05-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0004_testsuitcase_environment_testresult_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='request_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testresult',
            name='request_body',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
